// <auto-generated />
using System;
using EstudioJuridico.BD.Datos.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstudioJuridico.BD.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251025150621_Pruebacontroller")]
    partial class Pruebacontroller
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstudioJuridico.BD.Datos.Caso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("NumeroExpediente")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.CasoPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CasoId");

                    b.HasIndex("PersonaId");

                    b.ToTable("CasosPersona");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.Documentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoUrl")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CasoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoDocumentacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CasoId");

                    b.HasIndex("TipoDocumentacionId");

                    b.ToTable("Documentacions");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TasaJusticia_Aportes")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.TipoDocumentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumentos");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.CasoPersona", b =>
                {
                    b.HasOne("EstudioJuridico.BD.Datos.Caso", "Casos")
                        .WithMany("CasoPersonas")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstudioJuridico.BD.Datos.Persona", "Personas")
                        .WithMany("CasoPersonas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Casos");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.Documentacion", b =>
                {
                    b.HasOne("EstudioJuridico.BD.Datos.Caso", "Casos")
                        .WithMany("Documentacions")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstudioJuridico.BD.Datos.TipoDocumentacion", "TiposDocumentos")
                        .WithMany("Documentacions")
                        .HasForeignKey("TipoDocumentacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Casos");

                    b.Navigation("TiposDocumentos");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.Caso", b =>
                {
                    b.Navigation("CasoPersonas");

                    b.Navigation("Documentacions");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.Persona", b =>
                {
                    b.Navigation("CasoPersonas");
                });

            modelBuilder.Entity("EstudioJuridico.BD.Datos.TipoDocumentacion", b =>
                {
                    b.Navigation("Documentacions");
                });
#pragma warning restore 612, 618
        }
    }
}
